### PR TITLE
chore: rename brokerpaktestframework.ReturnTFState() to SetTFState()

### PR DESCRIPTION
**Pull request by zucchinidev**
[#181404871](https://www.pivotaltracker.com/story/show/181404871)

### Checklist:

* ~~[ ] Have you added or updated tests to validate the changed functionality?~~
* [x] Have you added Draft Release Notes in `docs/draft-release-notes.md`?
* [x] Have you followed the [Conventional Commits specification](https://www.conventionalcommits.org/en/v1.0.0/#summary)?

### CODE REVIEW

**Comment by zucchinidev** [comment]
I have reviewed `csb-brokerpak-[aws, azure]` and do not use the testing framework. The `csb-brokerpak-gcp` will be modified in a later pull request.

If you believe that it is not necessary to make parallel change and directly modify the method, or that I am wrong in this change, please let me know.

**Review by blgm — CHANGES_REQUESTED** [review]
Please add this in the draft release notes

**Comment by zucchinidev** [comment]
Thank you very much @blgm!! I just added the explanation in the draft releases notes.

**Review by blgm — APPROVED** [review]
Thanks

**Pull request merged**
