### PR TITLE
feat(experimental): store *.pem files alongside Terraform state

### PR DESCRIPTION
**Pull request by blgm**
To support TLS for GCP PostgreSQL, it proved necessary to write
*.pem files for the Terraform provider to use to connect as a client.

This feature is experimental and will change, as the files that are
stored alongside the Terraform state should be configurable.

[#181059797](https://www.pivotaltracker.com/story/show/181059797)

### Checklist:

* [X] Have you added or updated tests to validate the changed functionality?
* [X] Have you added Draft Release Notes in `docs/draft-release-notes.md`?
* [X] Have you followed the [Conventional Commits specification](https://www.conventionalcommits.org/en/v1.0.0/#summary)?

### CODE REVIEW

**Comment by jimbo459** [comment]
@blgm It wasn't immediately clear to me from the naming `AdditionalState` that this state can only contain .pem files. 
Would it make sense to make this more concrete i.,e `PEMFiles` - given that the current implementation only allows type of file?

**Review by jimbo459 — CHANGES_REQUESTED** [review]
See comment

**Comment by blgm** [comment]
> @blgm It wasn't immediately clear to me from the naming `AdditionalState` that this state can only contain .pem files. Would it make sense to make this more concrete i.,e `PEMFiles` - given that the current implementation only allows type of file?

I think that would make sense if there was never a plan to change this. But because this data gets stored in the database, any change would require a database migration. So if today we were to have:
```go
PEMFiles map[string][]byte `json:"pem_files"`
```
And tomorrow want to change it to:
```go
AdditionalState map[string][]byte `json:"additional_state"`
```
Then we would need to apply this change to the whole database on startup. This is entirely possible, but work that's easily avoided by being a bit more generic.

**Comment by jimbo459** [comment]
Makes a lot of sense @blgm - thanks for the clear explanation for the naming.

**Pull request merged**
